# Generated by Django 2.1.15 on 2021-02-04 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassPj',
            new_name='ClassProject',
        ),
        migrations.RenameField(
            model_name='classproject',
            old_name='namepj',
            new_name='nameproject',
        ),
        migrations.RenameField(
            model_name='classproject',
            old_name='professor',
            new_name='professorname',
        ),
    ]
