# Generated by Django 2.1.15 on 2021-02-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20210204_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='classproject',
            name='detailproject',
            field=models.TextField(default='Input Detail Project'),
        ),
    ]
