# Generated by Django 2.1.15 on 2021-02-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_classproject_detailproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=50)),
                ('list_name', models.CharField(max_length=50)),
                ('professor_name', models.CharField(max_length=50)),
                ('detail_project', models.TextField(default='HelloProject')),
            ],
        ),
    ]
