# Generated by Django 3.1.6 on 2021-02-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classproject',
            old_name='listname',
            new_name='listproject',
        ),
        migrations.RemoveField(
            model_name='classproject',
            name='detailproject',
        ),
        migrations.AlterField(
            model_name='project',
            name='detail_project',
            field=models.TextField(db_column='detail_project', max_length=3000),
        ),
        migrations.AlterField(
            model_name='project',
            name='list_name',
            field=models.CharField(db_column='list_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='name_project',
            field=models.CharField(db_column='name_project', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='professor_name',
            field=models.CharField(db_column='professor_name', max_length=50),
        ),
    ]
