# Generated by Django 3.1.6 on 2021-02-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20210216_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttopic',
            name='listproject',
            field=models.CharField(db_column='listproject', max_length=50),
        ),
        migrations.AlterField(
            model_name='projecttopic',
            name='nameprojectTopic',
            field=models.CharField(db_column='nameprojectTopic', max_length=50),
        ),
        migrations.AlterField(
            model_name='projecttopic',
            name='professorname',
            field=models.CharField(db_column='professorname', max_length=50),
        ),
        migrations.AlterField(
            model_name='projecttopic',
            name='year',
            field=models.CharField(db_column='year', max_length=50),
        ),
    ]
