# Generated by Django 2.2.10 on 2021-02-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20210216_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameExam', models.CharField(db_column='nameExam', max_length=50)),
            ],
            options={
                'ordering': ['nameExam'],
            },
        ),
        migrations.RemoveField(
            model_name='projecttopic',
            name='listproject',
        ),
        migrations.RemoveField(
            model_name='projecttopic',
            name='year',
        ),
    ]
